export const GET_COUNTRIES = 'GET_COUNNTRIES';
export const FILTRADO_CONTINENTS= 'FILTRADO_CONTINENTS';
export const GET_ACTIVITY= 'GET_ACTIVITY';
export const BY_ACTIVITY='BY_ACTIVITY';
export const BY_ALFB= 'BY_ALFB';
export const BY_POBLACION='BY_POBLACION';
export const POST_ACTIVITY= 'POST_ACTIVITY';
export const GET_NAME_COUNTRIES= 'GET_NAME_COUNTRIES';
export const DETAIL_COUNTRIES= 'DETAIL_COUNTRIES';
export const FAILURE = 'FAILURE';
export const CLEAR= 'CLEAR';




